# Generated by Django 2.1.5 on 2020-07-06 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 9, 58, 28, 5675), verbose_name='date published'),
        ),
    ]
